### PR TITLE
yarn berry pnp support

### LINKED ISSUE #1: Probably does not work with monorepos or/and yarn pnp
Hi, i think this plugin not really works with monorepos and yarn pnp. Would you consider a PR from my side?

### PR DESCRIPTION
**Pull request by mufasa71**
Resolves #1

### CODE REVIEW

File: index.ts [hunk 1]
```diff
@@ -25,7 +26,28 @@ export default function externalizeAllPackagesExcept(noExternals: string[]) {
...
+								    		}
+								  	}
+								}
+							} else {
+								// probably this don't need to be resolved
+								// as it may cause to resolve to transitive deps which is mistake
+								// possible check if package.json includes this dependency may work too
+
+								require.resolve(maybePackageName);
+							}
```
Comment (mayank99) [inline index.ts]: could you move this whole thing into a helper function at the bottom of the file? and then we only need to pass it `maybePackageName`

Comment (mufasa71) [reply index.ts]: Sure, done 👍

**Comment by mayank99** [comment]
thanks
